DROP TABLE departments   IF EXISTS;
DROP TABLE employees     IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ  AS INTEGER  START WITH 100000;


CREATE TABLE departments
(
  id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  fullName  VARCHAR (255)
);

CREATE TABLE employees
(
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  fullName          VARCHAR(255),
  birthday      TIMESTAMP,
  salary        INTEGER NOT NULL,
  department_id INTEGER NOT NULL,
  FOREIGN KEY (department_id) REFERENCES employees (id)
    ON DELETE CASCADE

);


CREATE UNIQUE INDEX employees_unique_date_idx ON employees (department_id, birthday)